### ISSUE TITLE
[FEATURE] Editable probabilities

### ISSUE THREAD

**Issue by Grygon** [ardittristan/VTTNPCGen#1]
First off loving this, super handy during my last session.

Second, a really neat feature I'd love to see is the ability to tweak probabilities for each option in the JSON. Probably the simplest way would be to add a custom "probability" key, although that's just a thought.

The ability to tweak it so it's accurate for the city/region's demographics would make this way more useful, so I can generate, for example, 80% dwarves in a dwarven capitol.

EDIT: Or even better (although maybe more difficult), allow it to roll on a table for a given value.

**Comment by ardittristan** [comment]
I'll take a look at it after i finish my current project!
