### ISSUE TITLE
Store/load probabilities

### ISSUE THREAD

**Issue by SWW13** [ardittristan/VTTNPCGen#10]
The probabilities are not stored between sessions and the default of everything having the same probability isn't that useful in most cases.

Would it be possible to either add a load/save function or change the current "defaults"?

**Comment by ardittristan** [comment]
Hm, are you maybe removing browser data between sessions? probabilities should be stored in browser storage like all other settings for npc gen. Is there maybe any errors in the console when pressing the generate button?

**Comment by SWW13** [comment]
Ah that explains it. I frequently switch devices / browser and don't need to create NPC's often, so I never used it on the same device and browser twice so far. I verified this works on the same browser now.

But it's still an issue for me to set up values on all devices. I'm not sure what would be the easiest / most useful way to implement this. Probably an export/import of the settings as a JSON file, I think this would benefit also some other users.

**Comment by SWW13** [comment]
Works like a charm, thanks :)
