### ISSUE TITLE
Own set of names

### ISSUE THREAD

**Issue by radkonf** [ardittristan/VTTNPCGen#13]
hi, 
I'm not expert programmer, but as far I see I cant put an list of names to choose from. 
I play in a greek themd world and can't use the names generated there

**Comment by ardittristan** [comment]
That can be done under the `Custom Generator Entries` setting.
If you don't want any of the pre-provided names to show next to your own names, you can toggle that at the bottom of the settings window, make sure it's on 
![image](https://user-images.githubusercontent.com/42787508/109395721-21f39480-792e-11eb-882a-040af7c839d1.png)

As to putting the names in, under the Names tab in the settings window there's already a bit of a beginning, but I'll provide another example if you don't care what race the names will show up on, if you do, you should replace `All` with the race

```json
{
    "First": {
        "Male": {
            "All": [
				"Firstname1",
				"Firstname2"
			]
        },
        "Female": {
            "All": [
				"Firstname1",
				"Firstname2"
			]
        }
    },
    "Last": {
    	"All": [
			"Lastname1",
			"Lastname2"
		]
    }
}
```

I hope this is enough info to push you into the right direction!

**Comment by radkonf** [comment]
Thank you that's AWESOME 
after some typos  „ instead of "  (Damm your word) and errors on my behalf. It works 
Almost :( 
Only 1 in ten has a name all others are blank. I can't see a patter - race doesn't seem like one 
Any idea what I'm doing wrong ?

**Comment by radkonf** [comment]
Okay I found how the error works. gender it seems to ignore male/females
`{
    "First": {
        "male": {
                "All": [
                        "Aaron",
                        "Zane"
                    ]
			},
        "Female": {
                "All": [
                        "Adara",
                           "Xylia"
			]
        }
    },
    "Last": {
        "All": [""]
    
    }
}`
That's "my" version. (al lot of more names though.)
It seems to ignore the male/female names, it only generates names for non-binary ( BTW great, that you implemented that option ) 
Work around: I just use non-binaries 🤷 
any ideas?

**Comment by ardittristan** [comment]
hm, Male should be with capital M, dunno why it ignores female though

**Comment by ardittristan** [comment]
What's the status on this? Is it still an issue or can I close it?

**Comment by radkonf** [comment]
Close it. I might open a new one. tackling the same issue. 
You've answered my question and I need to try it. ATM only nonbinary are getting names. I assume the error is on my side, because I can't code right. 
I'll look into it. and I can live wih the workaround. 
I'm sorry it takes so long to answering. Work sux ;) 
You're doing awesome job with the modlue, even better after the update.
