### ISSUE TITLE
Window not resizeable 

### ISSUE THREAD

**Issue by radkonf** [ardittristan/VTTNPCGen#17]
When I try to resize the main window is only resizable sideway ( x-Axis) not up/down (y-Axis) 
Tested with 
-chrome 89 (
- edge 
- Opera 

Do you need any more information ?

**Comment by ardittristan** [comment]
This is done on purpose since the CSS falls apart if you resize the y-Axis.

**Comment by radkonf** [comment]
ahh it's not a bug it's a feature :)
