### ISSUE TITLE
I miss some data in the saved actor sheet

### ISSUE THREAD

**Issue by JJBocanegra** [ardittristan/VTTNPCGen#2]
First I want to say that the idea of this module is fantastic and that it can become an indispensable module :).

And now to the problem, when generating a character it shows data like race, profession, or "proficiencies" that don't appear later in the actor that is saved.

It would be enough if these data appeared in the biography tab of the actor.

**Comment by ardittristan** [comment]
it might be some issue with the sheet you are using, are there any errors in the console?
race + profession
![image](https://user-images.githubusercontent.com/42787508/89650268-78ca4b80-d8c2-11ea-90ce-e3f63a460d01.png)

proficiencies:
![image](https://user-images.githubusercontent.com/42787508/89650312-87186780-d8c2-11ea-84ce-bfa6106b7bc1.png)

everything that doesn't have a seperate sheet field and is in the bio
![image](https://user-images.githubusercontent.com/42787508/89650359-97c8dd80-d8c2-11ea-8e21-ff364344d2e3.png)

**Comment by JJBocanegra** [comment]
I even did a new world with no modules to try it and it's the same, here is the proof

![image](https://user-images.githubusercontent.com/5797636/89650720-23426e80-d8c3-11ea-84e5-22d8ec4f557c.png)
![image](https://user-images.githubusercontent.com/5797636/89650750-2f2e3080-d8c3-11ea-9ccd-ae131a6691a1.png)
![image](https://user-images.githubusercontent.com/5797636/89650767-35241180-d8c3-11ea-98e4-48867bce080e.png)

**Comment by ardittristan** [comment]
found the issue, if saved as npc it does not fill in those fields, will look into fixing (it works when saved as character)

**Comment by JJBocanegra** [comment]
I am sorry but where is the option to save as character? It always saves as NPC 🤔

**Comment by ardittristan** [comment]
I set the default of the setting to save as character now. Do have a fix ready that I'll push in a sec, but I think it being integrated into the sheet looks better than being in the biography.

**Comment by ardittristan** [comment]
oh shit, update has an error, one moment

**Comment by ardittristan** [comment]
should be fixed now

**Comment by JJBocanegra** [comment]
Yes! I can see the race on the upper NPC sheet right now and the profession and proficiencies in the biography, that will work :)

Thanks!
