### ISSUE TITLE
Feature request: NPCs generate as NPC

### ISSUE THREAD

**Issue by PupperooX** [ardittristan/VTTNPCGen#22]
NPCs currently generate as player characters which makes this incompatible with Loot Sheet NPC, which is a real shame, and hopefully not too much of a fix?

**Comment by ardittristan** [comment]
There's already a setting for that!  
![image](https://user-images.githubusercontent.com/42787508/117516785-4d33d900-af9a-11eb-83d6-fc9c90c1061f.png)
