### ISSUE TITLE
Own set of names 2nd try :)  (low prio) 

### ISSUE THREAD

**Issue by radkonf** [ardittristan/VTTNPCGen#23]
hi 
I've tried your code: 
{
    "First": {
        "Male": {
            "All": [
				"Firstname1",
				"Firstname2"
			]
        },
        "Female": {
            "All": [
				"Firstname1",
				"Firstname2"
			]
        }
    },
    "Last": {
    	"All": [
			"Lastname1",
			"Lastname2"
		]
    }
}

![image](https://user-images.githubusercontent.com/79762867/117034017-3031a880-ad03-11eb-8e3c-70830775d1f0.png)
![image](https://user-images.githubusercontent.com/79762867/117034218-5eaf8380-ad03-11eb-8d2e-33d38e16a8e6.png)

Again with male/female I get no Firstname
With non-binary  I do get a Firstname 
(just a side note I changed the to FIrstnameFemale / FIrstnameMale - the non-binary selects from both 
I still don't get it :)

**Comment by ardittristan** [comment]
Am able to replicate now, will look into it!

**Comment by ardittristan** [comment]
Turns out there was a capitalization mistake, is fixed, though only on the foundry 0.8 version.
If you want to fix it in the 0.7 version you should replace `all` on this line with `All` https://github.com/ardittristan/VTTNPCGen/blob/0.5.0_fix/modules/applications/NPCGenerator.js#L963

**Comment by radkonf** [comment]
Awsome
works like a charm, didn#t expected that you do that. Could have waited so even more thanks: )
