### ISSUE TITLE
[Request] Wildcard/Folder Support for Images when generating NPC

### ISSUE THREAD

**Issue by Bigotacon** [ardittristan/VTTNPCGen#25]
As a DM I would like to pull from a group of random images from a directory or a regular expression so that each type (race/class) doesn't always come up with the same image.

**Comment by baileywick** [comment]
I second this. Using a wildcard would also allow me to more easily manage a library of images, where more often the race and gender is embedded inside the token file name, rather than having to always put them into very specific folders.

**Comment by ardittristan** [comment]
directory paths already include all subdirectories, so I added regex support for file names!
