### ISSUE TITLE
[Question] NPC vs PC Character Sheet

### ISSUE THREAD

**Issue by SirMotte** [ardittristan/VTTNPCGen#32]
You mention in the settings area of this module, that using a PC Character Sheet resolves some potential incompatibilities.
Could you elaborate further what you mean by this?

Also on a more fundamental note, is there any reason to use NPC sheets at all in Foundry? I could not think of any consequence but for modules that require NPC sheets to function properly (e.g. loot modules).

Thank you for this incredibly useful tool!

**Comment by ardittristan** [comment]
If I remember correctly npc sheets do not have resources for example, and some character stats. I have no idea why you would use the NPC sheet except for the combat rating field
