### ISSUE TITLE
Ability to reuse classes that are generated as items for each NPC

### ISSUE THREAD

**Issue by mr-bo-jangles** [ardittristan/VTTNPCGen#6]

**Comment by ardittristan** [comment]
Could you maybe explain what you mean with this?

**Comment by mr-bo-jangles** [comment]
Basically it's because of stuff like this.. I get a fresh one of these for
every generated NPC and I'm generating an entire city worth of NPC's
[image: image.png]

**Comment by ardittristan** [comment]
Thanks for the explanation! Could you maybe send the image directly through github or use an url instead? Images don't seem to work when coming from mail.
