### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'age' of undefined

### ISSUE THREAD

**Issue by adougherty** [ardittristan/VTTNPCGen#8]
I get the following error in the JavaScript console when trying to generate a new NPC:

`ClassBarbarian: false`
`ClassBard: false`
`ClassCleric: false`
`ClassDruid: false`
`ClassFighter: true`
`ClassMonk: false`
`ClassPaladin: false`
`ClassRanger: false`
`ClassRogue: false`
`ClassSorcerer: false`
`ClassWarlock: false`
`ClassWizard: false`
`GenderFemale: true`
`GenderMale: false`
`GenderNon-Binary: false`
`OrientationAsexual: false`
`OrientationBisexual: true`
`OrientationHeterosexual: true`
`OrientationHomosexual: true`
`ProbClassBarbarian: 1`
`ProbClassBard: 1`
`ProbClassCleric: 1`
`ProbClassDruid: 1`
`ProbClassFighter: 1`
`ProbClassMonk: 1`
`ProbClassPaladin: 1`
`ProbClassRanger: 1`
`ProbClassRogue: 1`
`ProbClassSorcerer: 1`
`ProbClassWarlock: 1`
`ProbClassWizard: 1`
`ProbGenderFemale: 1`
`ProbGenderMale: 1`
`ProbGenderNon-Binary: 1`
`ProbOrientationAsexual: 1`
`ProbOrientationBisexual: 1`
`ProbOrientationHeterosexual: 1`
`ProbOrientationHomosexual: 1`
`ProbProfessionEntertainer: 1`
`ProbProfessionLearned: 1`
`ProbProfessionLesser Nobility: 1`
`ProbProfessionMartial: 1`
`ProbProfessionProfessional: 1`
`ProbProfessionUnderclass: 1`
`ProbProfessionWorking Class: 1`
`ProbRaceDragonborn: 1`
`ProbRaceDwarf: 1`
`ProbRaceElf: 1`
`ProbRaceGnome: 1`
`ProbRaceHalf-Elf: 1`
`ProbRaceHalf-Orc: 1`
`ProbRaceHalfling: 1`
`ProbRaceHuman: 1`
`ProbRaceTiefling: 1`
`ProbRelationshipStatusDivorced: 1`
`ProbRelationshipStatusIn a relationship: 1`
`ProbRelationshipStatusMarried: 1`
`ProbRelationshipStatusMarried and having an affair: 1`
`ProbRelationshipStatusRecently broken up: 1`
`ProbRelationshipStatusRecently divorced: 1`
`ProbRelationshipStatusRecently widowed: 1`
`ProbRelationshipStatusSeeing someone who is married: 1`
`ProbRelationshipStatusSingle: 1`
`ProbRelationshipStatusWidowed: 1`
`ProbTraitBad Traits: 3`
`ProbTraitGood Traits: 3`
`ProfessionEntertainer: false`
`ProfessionLearned: false`
`ProfessionLesser Nobility: false`
`ProfessionMartial: true`
`ProfessionProfessional: false`
`ProfessionUnderclass: false`
`ProfessionWorking Class: false`
`RaceDragonborn: false`
`RaceDragonbornFirstNameForced: true`
`RaceDragonbornLastNameForced: true`
`RaceDwarf: false`
`RaceDwarfFirstNameForced: true`
`RaceDwarfLastNameForced: true`
`RaceElf: false`
`RaceElfFirstNameForced: true`
`RaceElfLastNameForced: true`
`RaceGnome: false`
`RaceGnomeFirstNameForced: true`
`RaceGnomeLastNameForced: true`
`RaceHalf-Elf: true`
`RaceHalf-ElfFirstNameForced: true`
`RaceHalf-ElfLastNameForced: true`
`RaceHalf-Orc: false`
`RaceHalf-OrcFirstNameForced: true`
`RaceHalf-OrcLastNameForced: true`
`RaceHalfling: false`
`RaceHalflingFirstNameForced: true`
`RaceHalflingLastNameForced: true`
`RaceHuman: false`
`RaceHumanFirstNameForced: true`
`RaceHumanLastNameForced: true`
`RaceTiefling: false`
`RaceTieflingFirstNameForced: true`
`RaceTieflingLastNameForced: true`
`RelationshipStatusDivorced: true`
`RelationshipStatusIn a relationship: true`
`RelationshipStatusMarried: true`
`RelationshipStatusMarried and having an affair: true`
`RelationshipStatusRecently broken up: true`
`RelationshipStatusRecently divorced: true`
`RelationshipStatusRecently widowed: true`
`RelationshipStatusSeeing someone who is married: true`
`RelationshipStatusSingle: true`
`RelationshipStatusWidowed: true`
`TraitBad Traits: true`
`TraitGood Traits: true`
`level: 1`
`useSubclass: false`

`0: ["Female"]`
`1: (2) ["Good Traits", "Bad Traits"]`
`2: ["Martial"]`
`3: (10) ["Single", "In a relationship", "Married", "Divorced", "Widowed", "Recently broken up", "Recently divorced", "Recently widowed", "Seeing someone who is married", "Married and having an affair"]`
`4: (3) ["Heterosexual", "Bisexual", "Homosexual"]`
`5: (19) ["DragonbornFirstNameForced", "DragonbornLastNameForced", "DwarfFirstNameForced", "DwarfLastNameForced", `
`"ElfFirstNameForced", "ElfLastNameForced", "GnomeFirstNameForced", "GnomeLastNameForced", "HalflingFirstNameForced", `
`"HalflingLastNameForced", "Half-Elf", "Half-ElfFirstNameForced", "Half-ElfLastNameForced", "Half-OrcFirstNameForced", "Half-`
`OrcLastNameForced", "HumanFirstNameForced", "HumanLastNameForced", "TieflingFirstNameForced", `
`"TieflingLastNameForced"]`
`6: ["Fighter"]`

`NPCGenerator.js:758 Uncaught (in promise) TypeError: Cannot read property 'age' of undefined`
`    at NPCGenerator.generateAge (NPCGenerator.js:758)`
`    at NPCGenerator.generateNPC (NPCGenerator.js:471)`
`    at NPCGenerator._updateObject (NPCGenerator.js:285)`
`    at NPCGenerator._onSubmit (foundry.js:5255)`
`    at Object.trigger (jquery.min.js:2)`
`    at HTMLFormElement.<anonymous> (jquery.min.js:2)`
`    at Function.each (jquery.min.js:2)`
`    at S.fn.init.each (jquery.min.js:2)`
`    at S.fn.init.trigger (jquery.min.js:2)`
`    at HTMLButtonElement.<anonymous> (NPCGenerator.js:301)`

**Comment by ardittristan** [comment]
from having a quick look, this might be because you have no races selected, thus it can't find the age since that's connected to race.

**Comment by adougherty** [comment]
I tested to make sure this was the issue. 

Test:

1. Click Generate NPC
2. Uncheck all Races except "Half-Elf"
3. Click "Generate"

The error occurs.

**Comment by ardittristan** [comment]
I am able to reproduce, it has something to do with the forced names, as a temporary measure till a fix you can disable all the forced names so it only chooses names from the current race.
